# Generated by Django 6.0.2 on 2026-02-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtokenindex',
            name='external_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
