# Generated by Django 6.0.2 on 2026-02-21 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_searchtokenindex_external_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSearchAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_hash', models.CharField(max_length=64)),
                ('total_matches', models.IntegerField(default=0)),
                ('returned_count', models.IntegerField(default=0)),
                ('truncated', models.BooleanField(default=False)),
                ('execution_time_ms', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_search_logs', to='documents.auditor')),
            ],
        ),
    ]
