# Generated by Django 6.0.2 on 2026-02-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_externalsearchaudit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalsearchaudit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='externalsearchaudit',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='externalsearchaudit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalsearchaudit',
            name='success',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='externalsearchaudit',
            index=models.Index(fields=['auditor'], name='documents_e_auditor_37e5e2_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsearchaudit',
            index=models.Index(fields=['created_at'], name='documents_e_created_b7a287_idx'),
        ),
        migrations.AddIndex(
            model_name='externalsearchaudit',
            index=models.Index(fields=['success'], name='documents_e_success_c73b80_idx'),
        ),
    ]
